---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore:
      - 'master'

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base for Team TEAM-VDI
    # Set the agent to run on
    runs-on: ubuntu-latest